/**
 * @readonly
 * @enum
 */
const ERROR_CODE = {
  AUTHERR: 'AUTHORIZATION_ERROR',
  NOAUTHERR: 'MISSING_AUTHORIZATION',
  INVLDAUTHTOKEN: 'INVALID_AUTH_TOKEN',
  INACTIVEACCT: 'INACTIVE_ACCOUNT',
  EXPIREDTOKEN: 'EXPIRED_TOKEN',
  INVLDREQ: 'INVALID_REQUEST',
  PERMERR: 'PERMISSION_ERROR',
  LIMITERR: 'LIMIT_ERROR',
  FEEERR: 'FEE_ERROR',
  NOTFOUND: 'RESOURCE_NOT_FOUND',
  APPERR: 'APPLICATION_ERROR',
  HTTPREQERR: 'INTERNAL_REQ_ERROR',
  DUPLRCRD: 'DUPLICATE_RECORD',
  VALIDATIONERR: 'VALIDATION_ERROR',
  INVLDDATA: 'INVALID_REQUEST_DATA',
  RTLIMERR: 'RATE_LIMIT_ERROR',
};

const ERROR_STATUS_CODE_MAPPING = {
  AUTHORIZATION_ERROR: 401,
  MISSING_AUTHORIZATION: 401,
  INVALID_AUTH_TOKEN: 401,
  INACTIVE_ACCOUNT: 401,
  EXPIRED_TOKEN: 401,
  PERMISSION_ERROR: 401,
  INVALID_REQUEST: 403,
  LIMIT_ERROR: 403,
  FEE_ERROR: 403,
  RESOURCE_NOT_FOUND: 404,
  DUPLICATE_RECORD: 409,
  APPLICATION_ERROR: 500,
  RATE_LIMIT_ERROR: 429,
};

const CUSTOM_ERROR_CODE = {
  SL02: 'Slug is already taken',
  AC01: 'access_code is required when access_type is private',
  AC05: 'access_code can only be set on private cards',
  AC03: 'This card is private, an access code is required',
  AC04: 'Invalid access code',
  NF01: 'Creator Card not found',
  NF02: 'Creator Card not found',
};

const CUSTOME_ERROR_CODE_MAPPING = {
  SL02: 'SLO2',
  AC01: 'AC01',
  AC05: 'ACO5',
  AC03: 'AC03',
  AC04: 'AC04',
  NF01: 'NF01',
  NF02: 'NF02',
};

module.exports = {
  ERROR_CODE,
  ERROR_STATUS_CODE_MAPPING,
  CUSTOM_ERROR_CODE,
  CUSTOME_ERROR_CODE_MAPPING,
};
